### ISSUE TITLE
Need help with test_ulens.py

### ISSUE THREAD

**Issue by jenniferyee** [jdeast/EXOZIPPy#1]
TestGRAVITYEvent needs someone to calculate the source and lens velocities in km/s in the heliocentric frame and a value for rho and Rsource (in Solar radii). Then, this unit test will test all aspects of the conversions from physical to microlensing space.

https://ui.adsabs.harvard.edu/abs/2020ApJ...897..180Z/abstract

**Comment by rpoleski** [comment]
Lens velocity (hel frame, (N, E), km/s): 
`-58.5 +- 3.0`
`27.3 +- 1.8`
Same for source:
`-21.1 +- 1.3`
`-2.62 +- 0.76`
Rho and Rsource are provided by [Fukui et al. (2019)](https://ui.adsabs.harvard.edu/abs/2019AJ....158..206F/abstract):
`rho/1000 = 4.567 +- 0.071`
and after scaling to Zang's D_s, the source radius is:
`R_source = 1.29 +- 0.22 R_Sun`

**Comment by jenniferyee** [comment]
commit 46d63a7
For the lens velocity, mmexofast gives:

E       Max absolute difference: 0.25249024
E       Max relative difference: 0.00431607
E        x: array([-58.75249 ,  27.230732])
E        y: array([-58.5,  27.3])

The rho values are also off by a similar percentage. Is this an acceptable level of error? (being about 10% of the statistical error)

**Comment by rpoleski** [comment]
I've investigated the differences in detail. There were some inconsistencies of other parameters used, or I provided values rounded more than you. I've corrected the reference values ([095c82a](https://github.com/jdeast/EXOZIPPy/commit/095c82a2bd226d8dc194a0709d9a74fe655a0cce)) and these tests pass now.
