### ISSUE TITLE
Example 03 Needs YAML

### ISSUE THREAD

**Issue by jenniferyee** [jdeast/EXOZIPPy#4]
Example 03 needs the MMEXOFAST inputs (data files, priors, coords, etc., but NOT the expected values) rewritten as a YAML file(s) so that the bandpass can be linked to the dataset. This would also serve to replace Example 04.

**Comment by rpoleski** [comment]
First, I'll make the user to calculate `np.rad2deg(2.756)`. 
Second, I don't get this:
file_1 = os.path.join(dir_, "OGLE_I.dat **mag**")
Do you want a file path and " mag" in the same string?

**Comment by jenniferyee** [comment]
the "mag" is probably a typo.

**Comment by rpoleski** [comment]
Done in [c1fd417](https://github.com/jdeast/EXOZIPPy/commit/c1fd417ce738cc13594b2b71197149d61bb4981f).
It can be further developed for ephemeris etc.

**Comment by rpoleski** [comment]
Finished in 0ee40ad
